// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDZhKx3vbDkHcMfq85ifpQm7n9ymiZ8p10',
    appId: '1:962423998993:web:7b0138ae4a53df1e75bfb0',
    messagingSenderId: '962423998993',
    projectId: 'aidbridge-74ec0',
    authDomain: 'aidbridge-74ec0.firebaseapp.com',
    storageBucket: 'aidbridge-74ec0.firebasestorage.app',
    measurementId: 'G-LJGNNXQB2K',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCXOIwb8NfK_HOaK5G-y1sUIQY5rjfUi3E',
    appId: '1:962423998993:ios:16776e7488bbf72c75bfb0',
    messagingSenderId: '962423998993',
    projectId: 'aidbridge-74ec0',
    storageBucket: 'aidbridge-74ec0.firebasestorage.app',
    iosBundleId: 'com.example.majorNgo',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDZhKx3vbDkHcMfq85ifpQm7n9ymiZ8p10',
    appId: '1:962423998993:web:efda2c7a51c1e9ed75bfb0',
    messagingSenderId: '962423998993',
    projectId: 'aidbridge-74ec0',
    authDomain: 'aidbridge-74ec0.firebaseapp.com',
    storageBucket: 'aidbridge-74ec0.firebasestorage.app',
    measurementId: 'G-BM7K3XSYP3',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCXOIwb8NfK_HOaK5G-y1sUIQY5rjfUi3E',
    appId: '1:962423998993:ios:16776e7488bbf72c75bfb0',
    messagingSenderId: '962423998993',
    projectId: 'aidbridge-74ec0',
    storageBucket: 'aidbridge-74ec0.firebasestorage.app',
    iosBundleId: 'com.example.majorNgo',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAbsS2umxKTgC_G6zjtEj-2we5GDPMlWgk',
    appId: '1:962423998993:android:72269f429ff78f4075bfb0',
    messagingSenderId: '962423998993',
    projectId: 'aidbridge-74ec0',
    storageBucket: 'aidbridge-74ec0.firebasestorage.app',
  );

}